### ISSUE TITLE
Adding elements in bulk to `EntityList`

### ISSUE THREAD

**Issue by arthef** [shannah/CodeRAD#15]
Hi,

I use `EntityList` for maintaining and displaying contact list. I may have 100 or more contacts. During app startup time, the app connects to the server and loads entire contact list.
Now, adding contacts to `EntityList`, one by one is very slow and inefficient. it would be much more efficient to add all contacts to the list and then redraw the contacts view.

I cannot find any method in `EntityList` for adding multiple elements in one call. But, maybe this is not the best approach any way. Maybe there is a way to somehow block the view from updating while the elements are being added to the `EntityList`?

What would be the best way to add many elements to `EntityList` in efficient way?

**Comment by shannah** [comment]
I'm working on a solution for this and will have it committed today.

The gist:

~~~~
myList.startTransaction();  // Fires a TransactionEvent to listeners to indicate that a transaction has started.
//..  a bunch of add/remove calls on the list.
myList.commitTransaction();  // Fires a TransactionEvent to listeners to indicate that a transaction has ended.


//... Listeners 

public void actionPerformed(EntityListEvent evt) {
    if (evt instanceof EntityAddedEvent) {

        if (evt.getTransaction() != null) {
              // This is part of a transaction... wait until the transaction is done to process it.

        } else {
              // Process the add

        }
        return;
    }

     if (evt instanceof EntityRemovedEvent) {

        if (evt.getTransaction() != null) {
              // This is part of a transaction... wait until the transaction is done to process it.

        } else {
              // Process the remove

        }
        return;
    }

    if (evt instanceof TransactionEvent) {
        TransactionEvent te = (TransactionEvent)evt;
         if (te.isComplete()) {
              for (EntityEvent subEvent : te) {
                      // subEvent is either an EntityAddedEvent or EntityRemovedEvent
                      // process them here.
              }
         }
         return;
    }

    
}
~~~~


Using this solution, components that rely on the EntityAddedEvents and EntityRemoveEvents for keeping in sync with the list will still work.  It does, however, provide the option for components to take advantage of transactions to be able to defer response until a transaction is complete.

Will this solution suffice for your needs?

**Comment by shannah** [comment]
I've committed support for the transactions.  See the [Unit tests](https://github.com/shannah/CodeRAD/blob/master/CodeRADTests/src/com/codename1/rad/tests/EntityListTest.java#L105-L231) for some example usage.

Also see the [TransactionEvent javadocs](https://shannah.github.io/CodeRAD/javadoc/com/codename1/rad/models/EntityList.TransactionEvent.html) for some example code.

**Comment by arthef** [comment]
Thank you for lighting quick turn around and providing new version of the code.

I tried it and it works but I may still be missing something. I actually applied your example to the EntityList side of logic, that is starting transaction, adding build Entities and committing transaction.

However, from the GUI point of view this changes little to nothing. All the changes are being processed one by one and it takes long time for all contacts to be loaded into GUI.

I guess I am missing something on the GUI side. I use `CodeRAD` and `AbstractEntityView` for displaying contact list. It is partially based on the `ChatRoomView` from `RADChatRoom` project. That is, I use `EntityListView` to draw list of Entities. So, my question is:
Is there a support for EntityList transaction already built-in into the `EntityListView` or I have to add some logic on the GUI in order to handle transactions properly?

**Comment by shannah** [comment]
I haven't added support for transactions into EntityListView yet.  I can do that tomorrow.

The way I implemented transactions, existing views that weren't designed for transactions will still work- they just won't take advantage of transactions for optimized sync.  I intend to update all of the core views to support transactions eventually.

**Comment by arthef** [comment]
Ok, this is what I thought.

If you can and plan to update EntityListView tomorrow, I can wait but if you are busy now and plan to postpone it for later, I would be grateful for some hints and directions on how to do it and I would add something myself.

**Comment by shannah** [comment]
I've updated EntityListView to support transactions now.  I've also added a sample to CodenameOne samples to demonstrate this:
https://github.com/codenameone/CodenameOne/commit/dedc57f0e80b981c1121231e3772676e112731e7

**Comment by arthef** [comment]
Thank you very much. The GUI now works as expected.

I guess, there is still not recommended to call `addAll` on the EntityList?

One issue I am still facing is the order of items. I have a custom implementation of the internalList in the EntityList and I can take care of the items order. Contacts are being added in random order but in the internal list they endup ordered alphabetically.
However, `EntityListView` displays items in a different order. Perhaps in the order in which items were being added.

Is there any way to make the `EntityListView` redisplay all items in a correct order, that is order in which items are actually stored in the EntityList's internalList?

**Comment by shannah** [comment]
> I guess, there is still not recommended to call addAll on the EntityList?
I can add an addAll() method.  It will basically just wrap add() in a loop.

> However, EntityListView displays items in a different order. Perhaps in the order in which items were being added.
Ah.  Yes.  Currently the EntityAddedEvent assumes that the index of the newly added item will just be the "next" one (it uses size() just before adding the element to the list.  I can fix this to use indexOf() after the add so that it will get the actual index so that the view can insert it at the correct position. Since indexOf is more expensive. (it changes add() from `O(1)` to `O(n)`), I'd like to be able to do this conditionally so that it is only used in cases where the underlying list is sorted.  So I'd want to either add a boolean property to EntityLIst to indicate that it is "sorted".  

Although, at this point, we might as well just add support for a Comparator so that it can support sortability "natively".

**Comment by arthef** [comment]
Hm, yes. For this reason, I have already implemented my own internal `List` to sort all elements automatically as they are being added. This way I am sure I have all elements in the list in correct order.

Actually, this list is kind of a mix of `TreeMap` and `List`. `Map`'s functionality allows me to quickly find and get any item from the list plus the benefit of the automatic sorting. Adding new elements, one by one, to this `Collection` is actually very expensive, that's why I would prefer to be able to call `addAll`. However, the collection is modified very rarely, so it is not that of a big deal.

Anyway, as adding new elements is not frequent at all, I would be satisfied with a solution when I can somehow notify `EntityListView` to redraw entire list to ensure correct order.

**Comment by shannah** [comment]
I have fixed the issue with the Add  events triggering the view to add rows at the end of the list even if the entity was added in a different place in the list.

I also added an `invalidate()` method to EntityList that you can call to trigger a "revalidate" on registered views if you change your underlying list (e.g. using addAll()).

I added a [sample to demonstrate the use of invalidate() with a custom list implementation](https://github.com/codenameone/CodenameOne/blob/bf8bf1f7d06ee738ec3ffdc7c6c39354915427e7/Samples/samples/RADEntityListAddRemoveInvalidateSample/RADEntityListAddRemoveInvalidateSample.java) that should be directly applicable to your custom implementation.

I think this should address your request, as you can now load your underlying collection directly, and just call `invalidate()` to update the views.

**Comment by arthef** [comment]
Invalidate seems to do the trick. Thank you.

I wonder if I should call `commitTransaction()` and then call `invalidate()` or other way around. Right now I am calling `commitTransaction()` and then `invalidate()` but the result is that the list shows in incorrect order for a split second and then it redrawn in a correct order.
So, my guess is, maybe I should call `invalidate()` first but is it safe?

**Comment by arthef** [comment]
Ok, I have just tested it. If `invalidate()` is called before `commitTransaction()` then the list is actually messed up with some entries showing twice and the list is in incorrect order.
So, I guess, first `commit`, then `invalidate`. 

Am I correct?

**Comment by shannah** [comment]
`invalidate()` should really only be called if you've made changes directly to your internal list without going through the EntityLIst's API.  It basically sends a signal to all views saying "You need to refresh yourself from scratch."

`commitTransaction()` sends a signal to views saying "now you can process all of the add/remove events that have taken place since beginTransaction() was started".

You shouldn't use these together as it will confuse the view.

E.g.
beginTransaction()
...  add/remove calls
invalidate() ---> View will rebuild from scratch
commitTransaction() ---> View will process all of the add/removes since beginTransaction() which is wrong now because the view is already up-to-date due to the invalidate() call.

**Comment by shannah** [comment]
To make this clear, I think I'll make invalidate() throw an IllegalStateException if it is called inside a transaction.

**Comment by arthef** [comment]
OK, let me sum it up to make sure I understand intention.

* Transactions using EntityList API
beginTransaction()
...add bunch of items **to the end of the list** using the EntityList API
commitTransaction()

* Modifications not using EntityList API like addAll or other direct modifications of the internal list
invalidate()

Please note, from what I understand, from the code and from what I see in action, when using transactions and adding items which end up in a different positions, like for sorted lists or collections, when you commit transaction, the list would most likely display items in incorrect order. I did not test it but I am afraid that also, if you mix add/remove elements in the middle of the list within transactions this may display incorrect list altogether due to changing indexes of all elements.

So, maybe, a better solution would be handle `commitTransaction()` in such a way that it throws away all modification events and just process it the same way as invalidate() call?

**Comment by shannah** [comment]
For example, if you wanted to implement your efficient addAll() method, it would look something like this:

~~~~
public void addAll(Collection<Entity> entities) {
      internalCollection.addAll(entities);
      invalidate();
}
~~~~

No need for any transactions.  This method won't fire any add/remove/transaction events to the view.  It just adds all the items to the internal list that you're using.  Then it calls invalidate() to tell the views to update themselves.

**Comment by arthef** [comment]
Yes, this is probably what I really need, thank you.

**Comment by arthef** [comment]
Do I also need to call `setChanged()` in the above code?

**Comment by shannah** [comment]
> I did not test it but I am afraid that also, if you mix add/remove elements in the middle of the list within transactions this may display incorrect list altogether due to changing indexes of all elements.

Yes, you are right.  I need to fix this.

**Comment by shannah** [comment]
I have fixed the transactions issue now so that the view will correctly handle transactions with adds and removes.  Transactions will now "squash" their sub-events so that:

1. All remove events come before any add events.
2. Only "add" events corresponding to entities that *exist* in the model list at the time of the commit are included.  E.g. If an entity is added and then removed in the same transaction, the "remove" event will be delivered but not the "add" event.
3. `getIndex()` of "add" events will always be the correct current index (at the time of commit) for the corresponding entity in the event. 

`EntityListView` has been updated to handle these events properly.

> Do I also need to call setChanged() in the above code?

I have just updated `invalidate()` to call `setChanged()` so you don't need to.  But calling `setChanged()` twice won't cause any problems, if you're ever unsure.

**Comment by arthef** [comment]
Thank you for corrections. I have pulled the most recent code and tested it.

Unfortunately, from my tests, it looks like transactions do not display elements in a correct order.

To test it, I load list of contacts and sort it in reverse order in a separate `List`. Then, within transaction, add one by one to the `EntityList`. Adding is done in reverse order, and the `internalList` within `EntityList` has own sorting mechanism. So, while elements are being added, they are reordered within the `EntityList`. After calling `commitTransaction()`, entire list is displayed in incorrect order.
If, I then, call `invalidate()` on the `EntityList` the list is redrawn and all elements are in correct order.

**Comment by shannah** [comment]
I'll put together a test case for this. It was working for me in my current tests but I'm not actually using a custom sort on the internal list.  In theory that shouldn't make a difference - but apparently I missed something.

**Comment by arthef** [comment]
I just realized that a similar problem may actually affect regular `Entity`. Let's say, I have a user profile with many fields. When i receive contact's vCard and update user's profile I have to potentially modify many fields/properties in a single `Entity`.
Is there any way to set a bulk of properties for an entity without firing property changed event for each individual property?

**Comment by shannah** [comment]
I'll look into it. The events themselves shouldn't present much of an issue.  EntityViews use the Observer pattern so they aren't affected by PropertyChangeEvents.  PropertyViews are bound directly to their corresponding property so they aren't getting "noise" - and queuing changes doesn't change the overall expense.  The main performance issue is when these events trigger a UI revalidation.  If a view has 100 property views and they are all updated - and each one triggers a "revalidate()" call on the parent container or form, then that would be a big waste.  I think I can solve this in a more fundamental way.  E.g. queue all revalidates() until the end of the EDT "paint" cycle, and squash them into a minimal set of revalidate calls that would all be performed together.

**Comment by arthef** [comment]
Ok, thank you.

I have got `EntityList` working with a view showing elements in correct order and adding all items in bulk using `invalidate()`. So, from my point of view, for the `EntityList` the main issue is solved.

Feel free to close the ticket if you think there is nothing more to add to it.

**Comment by shannah** [comment]
I have fixed the issue with items being added in the wrong order in EntltyLIstView.

I've also done some work on efficiency for Entity property changes to prevent redundant UI revalidations.  I did this with 2 improvements:

1. All internal view calls to `revalidate()` or `revalidateWithAnimationSafety()` have been changed to the new `Container.revalidateLater()` method (which is in Git but won't be available until friday's CN1 update as it is part of the CN1 core.  `revalidate()` and `revalidateWithAnimationSafety()` trigger revalidations immediately. So if there are a lot of little views inside a parent view and they are all updated - each may trigger a revalidation for each property change, which is expensive and redundant.  `revalidateLater()` instead just marks the container for revalidation before the next paint cycle.  It also automatically removes reduntant revalidations.
2. I added the `AbstractEntityView.setBindOnPropertyChangeEvents(boolean)` which, when set to `false` will cause the view to bind using `addObserver()/deleteObserver()` rather than `addPropertyChangeListener()/removePropertyChangeListener()`.  I did this because, after inspecting the code I realized that EntityViews indeed were binding on PropertyChangeEvents and not using the Observer pattern, as I had indicated before.  The default behaviour is still to use PropertyChangeEvents, but you can now turn this off by calling `view.setBindOnPropertyChangeEvents(false)`.  Then the view's `update()` method will only be triggered by explicit calls to `notifyObservers()` on the model, which will be less noisy.

One other change I made in this commit is to make *binding* behaviour of views more customizable.  As you know, views are bound to their model in initComponent() and unbound in deinitialize().  This is to prevent memory leaks.  This, however, causes a problem if you want your view to stay in sync with your model when the view is not initialized (e.g. while a dialog is showing, or when the view is off screen - not part of the current form).  

I have now changed it so that you can explicitly call `bind()` and `unbind()` on a view to take control of this lifecycle.  `AbstractEntityView` keeps an internal counter that is incremented when `bind()` is called and decremented when `unbind()` is called so that binding only actually occurs when the counter is increased to `1`.  And unbinding only occurs when the counter is decremented to `0`.  So if you want the binding to be active even when the view is not initialized, you can just call `view.bind()` explicitly to do the binding.  You just need to remember to call `view.unbind()` when you're done to prevent memory leaks.  `bind()` and `unbind()` calls must balance each other out.  If you call `unbind()` when it is not bound, it will throw an `IllegalStateException`.

One note about this implementation.  `bind()` and `unbind()` are now `final` so they can't be overridden.  Subclasses should override `bindImpl()` and `unbindImpl()` instead.  These are only called the the binding is actually activated/deactivated (i.e. when the bind counter increments to 1 or decrements to 0 respectively).

**Comment by arthef** [comment]
Thank you for all these code. I probably need some time to process it and start using it. Especially bind/unbind seem like something I was looking for before and can benefit from.

However, one thought comes to my mind right away.
It might be difficult to track bind/unbind and make sure they are balanced. When, at some point I no longer need a view I could just call unbind many times until I get the exception to make sure it is reset to 0. But maybe we could have a method to reset the counter to 0 with a single call?

I will also test the view in observer mode, so see if there is any practical difference but I will wait until next week to make sure I have the new stuff from CN1 core.

**Comment by arthef** [comment]
I have got a new version of the code today, compiled and tested. Everything seems to work faster and overall GUI is more responsive. That's my impression.

Thanks a lot, good work!
